/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package online.movie.tv.show;

import java.util.Arrays;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sagor Ahamed
 */
public class AdminList extends javax.swing.JFrame {

    /**
     * Creates new form AdminPanel
     */
    public AdminList() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        AdminDatabaseHandler db = new AdminDatabaseHandler();
                 db.connectDatabase();
                 db.showAdminDetails(adminData,"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        adminPanelClose = new javax.swing.JLabel();
        adminPanelMin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        adminListUpdate = new javax.swing.JButton();
        adminListSearchValue = new javax.swing.JTextField();
        adminListSearch = new javax.swing.JButton();
        adminListBack = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        adminListAdd = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        adminData = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        adminListUName = new javax.swing.JTextField();
        adminListMobileNo = new javax.swing.JTextField();
        adminListEmail = new javax.swing.JTextField();
        adminListCountry = new javax.swing.JTextField();
        adminListGender = new javax.swing.JComboBox<>();
        adminListPAssword = new javax.swing.JPasswordField();
        jLabel28 = new javax.swing.JLabel();
        adminListType = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        adminListId = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        adminListDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setForeground(new java.awt.Color(0, 102, 255));

        adminPanelClose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        adminPanelClose.setForeground(new java.awt.Color(255, 255, 255));
        adminPanelClose.setText("X");
        adminPanelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminPanelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminPanelCloseMouseClicked(evt);
            }
        });

        adminPanelMin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        adminPanelMin.setForeground(new java.awt.Color(255, 255, 255));
        adminPanelMin.setText("_");
        adminPanelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminPanelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminPanelMinMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/movie/tv/show/images/i.png"))); // NOI18N
        jLabel1.setText("Tube");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(449, 449, 449)
                .addComponent(adminPanelMin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminPanelClose)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(adminPanelClose))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(adminPanelMin)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        adminListUpdate.setBackground(new java.awt.Color(255, 255, 255));
        adminListUpdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        adminListUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/movie/tv/show/images/Update.png"))); // NOI18N
        adminListUpdate.setText("Update");
        adminListUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminListUpdateActionPerformed(evt);
            }
        });

        adminListSearchValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adminListSearchValue.setToolTipText("");
        adminListSearchValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                adminListSearchValueKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                adminListSearchValueKeyTyped(evt);
            }
        });

        adminListSearch.setBackground(new java.awt.Color(51, 51, 51));
        adminListSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        adminListSearch.setForeground(new java.awt.Color(255, 255, 255));
        adminListSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/movie/tv/show/images/search.png"))); // NOI18N
        adminListSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminListSearchActionPerformed(evt);
            }
        });

        adminListBack.setBackground(new java.awt.Color(255, 255, 255));
        adminListBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        adminListBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/movie/tv/show/images/back.png"))); // NOI18N
        adminListBack.setText("Back");
        adminListBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminListBackActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(102, 102, 102));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("(Admin List)");

        adminListAdd.setBackground(new java.awt.Color(255, 255, 255));
        adminListAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        adminListAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/movie/tv/show/images/add.png"))); // NOI18N
        adminListAdd.setText("Insert");
        adminListAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminListAddActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        adminData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "User Name", "Email", "Mobile", "Password", "Country", "Gender", "Type"
            }
        ));
        adminData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(adminData);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("User Name:");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Email:");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Password:");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Country:");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Mobile No:");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Gender:");

        adminListUName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        adminListMobileNo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        adminListMobileNo.setToolTipText("+88017XXXXXXX");

        adminListEmail.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        adminListEmail.setToolTipText("someone@mail.com");

        adminListCountry.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        adminListGender.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        adminListGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        adminListGender.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminListGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminListGenderActionPerformed(evt);
            }
        });

        adminListPAssword.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Manage Details");

        adminListType.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Type:");

        adminListId.setEditable(false);
        adminListId.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("ID:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(adminListId, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel23)
                                .addComponent(jLabel26)
                                .addComponent(jLabel22)
                                .addComponent(jLabel21)
                                .addComponent(adminListUName, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(adminListEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(adminListMobileNo, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(1, 1, 1))
                        .addComponent(adminListPAssword, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel27)
                            .addComponent(jLabel25)
                            .addComponent(adminListCountry)
                            .addComponent(adminListGender, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adminListType)))
                    .addComponent(jLabel28))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminListId, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminListUName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminListEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminListMobileNo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminListPAssword, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(adminListCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminListGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminListType, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        adminListDelete.setBackground(new java.awt.Color(255, 255, 255));
        adminListDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        adminListDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/movie/tv/show/images/delete.png"))); // NOI18N
        adminListDelete.setText("Delete");
        adminListDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminListDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(adminListSearchValue, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminListSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(adminListUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(adminListDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(adminListAdd)
                        .addGap(127, 127, 127)
                        .addComponent(adminListBack, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adminListSearchValue, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adminListSearch)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 23, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminListAdd)
                    .addComponent(adminListUpdate)
                    .addComponent(adminListDelete)
                    .addComponent(adminListBack, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminPanelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminPanelMinMouseClicked
         this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_adminPanelMinMouseClicked

    private void adminPanelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminPanelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_adminPanelCloseMouseClicked

    private void adminListUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminListUpdateActionPerformed
            
        String uname,email,mobile,password,country;
       
        
        uname=adminListUName.getText();
        email=adminListEmail.getText();
        mobile=adminListMobileNo.getText();
        password=adminListPAssword.getText();
        country=adminListCountry.getText();
        String type=adminListType.getText();
        int id = Integer.valueOf(adminListId.getText());
        
        if (uname.equals("") || email.equals("") || mobile.equals("") || password.equals("") || country.equals("")) {
            JOptionPane.showMessageDialog(this, "Please select a field to update data");
        }else{
            char gender = ((adminListGender.getSelectedIndex()==0)?'M':'F');
            
                   AdminDatabaseHandler db = new AdminDatabaseHandler();
                    db.connectDatabase(); 
                     db.updateAdminData(id,uname,email,mobile,password,country,gender,type);
                     JOptionPane.showMessageDialog(this, "Admin Data Updated");
                     
                     //After data updated table will be refreshed
                       db.showAdminDetails(adminData, "");
                adminData.setModel(new DefaultTableModel(null, new Object[]{"ID","User Name","Email","Mobile","Password","Country","Gender","Type"}));
                 db.showAdminDetails(adminData, adminListSearchValue.getText());
                 adminListId.setText("");
                 adminListUName.setText("");
                 adminListEmail.setText("");
                 adminListEmail.setText("");
                 adminListMobileNo.setText("");
                 adminListPAssword.setText("");
                 adminListCountry.setText("");
                 adminListGender.setSelectedItem("Male");
 
        }
        
    }//GEN-LAST:event_adminListUpdateActionPerformed

    private void adminListSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminListSearchActionPerformed
         AdminDatabaseHandler db = new AdminDatabaseHandler();
                 db.connectDatabase();
                adminData.setModel(new DefaultTableModel(null, new Object[]{"ID","User Name","Email","Mobile","Password","Country","Gender","Type"}));
                 db.showAdminDetails(adminData, adminListSearchValue.getText());
    }//GEN-LAST:event_adminListSearchActionPerformed

    private void adminListBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminListBackActionPerformed
        
         AdminSettings settings = new AdminSettings();
            settings.setVisible(true);
            settings.pack();
            settings.setLocationRelativeTo(null);
            settings.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
    }//GEN-LAST:event_adminListBackActionPerformed

    private void adminListAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminListAddActionPerformed
       AdminRegister adminRegister = new AdminRegister();
            adminRegister.setVisible(true);
            adminRegister.pack();
            adminRegister.setLocationRelativeTo(null);
            adminRegister.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
    }//GEN-LAST:event_adminListAddActionPerformed

    private void adminListGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminListGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminListGenderActionPerformed

    private void adminListDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminListDeleteActionPerformed

        if (adminListId.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please Select a Row First");
        }else{
         AdminDatabaseHandler db=new AdminDatabaseHandler();
                    db.connectDatabase(); 
                     db.deleteAdminData(Integer.valueOf(adminListId.getText()));
                     JOptionPane.showMessageDialog(this, "Admin Data Deleted");
                     
                     //After data updated table will be refreshed
                        db.showAdminDetails(adminData, "");
                adminData.setModel(new DefaultTableModel(null, new Object[]{"ID","User Name","Email","Mobile","Password","Country","Gender","Type"}));
                 db.showAdminDetails(adminData, adminListSearchValue.getText());
                 adminListId.setText("");
                 adminListUName.setText("");
                 adminListEmail.setText("");
                 adminListEmail.setText("");
                 adminListMobileNo.setText("");
                 adminListPAssword.setText("");
                 adminListCountry.setText("");
                 adminListGender.setSelectedItem("Male");
    }
    }//GEN-LAST:event_adminListDeleteActionPerformed

    private void adminDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminDataMouseClicked
        int rowIndex=adminData.getSelectedRow();
        
        DefaultTableModel model = (DefaultTableModel) adminData.getModel();
        adminListId.setText(model.getValueAt(rowIndex, 0).toString());
        adminListUName.setText(model.getValueAt(rowIndex, 1).toString());
        adminListEmail.setText(model.getValueAt(rowIndex, 2).toString());
        adminListMobileNo.setText(model.getValueAt(rowIndex, 3).toString());
        adminListPAssword.setText(model.getValueAt(rowIndex, 4).toString());
      adminListCountry.setText(model.getValueAt(rowIndex, 5).toString());
        if (model.getValueAt(rowIndex, 6).toString().equals("M")) {
            adminListGender.setSelectedItem("Male");
        }else{
             adminListGender.setSelectedItem("Female");
        }
        
        //userListGender.setText(model.getValueAt(rowIndex, 0));
        adminListType.setText(model.getValueAt(rowIndex, 7).toString());
    }//GEN-LAST:event_adminDataMouseClicked

    private void adminListSearchValueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adminListSearchValueKeyTyped
            AdminDatabaseHandler db=new AdminDatabaseHandler();
                 db.connectDatabase();
                 adminData.setModel(new DefaultTableModel(null, new Object[]{"ID","User Name","Email","Mobile","Password","Country","Gender","Type"}));
                 db.showAdminDetails(adminData, adminListSearchValue.getText());
    }//GEN-LAST:event_adminListSearchValueKeyTyped

    private void adminListSearchValueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adminListSearchValueKeyPressed
        
    }//GEN-LAST:event_adminListSearchValueKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable adminData;
    private javax.swing.JButton adminListAdd;
    private javax.swing.JButton adminListBack;
    private javax.swing.JTextField adminListCountry;
    private javax.swing.JButton adminListDelete;
    private javax.swing.JTextField adminListEmail;
    private javax.swing.JComboBox<String> adminListGender;
    private javax.swing.JTextField adminListId;
    private javax.swing.JTextField adminListMobileNo;
    private javax.swing.JPasswordField adminListPAssword;
    private javax.swing.JButton adminListSearch;
    private javax.swing.JTextField adminListSearchValue;
    private javax.swing.JTextField adminListType;
    private javax.swing.JTextField adminListUName;
    private javax.swing.JButton adminListUpdate;
    private javax.swing.JLabel adminPanelClose;
    private javax.swing.JLabel adminPanelMin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
