/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package online.movie.tv.show;

import static java.lang.Integer.max;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.UUID;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.concurrent.ThreadLocalRandom;
/**
 *
 * @author Sagor Ahamed
 */
public class Payments extends javax.swing.JFrame {

    /**
     * Creates new form AdminPanel
     */
    public Payments() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        AdminDatabaseHandler db = new AdminDatabaseHandler();
                 db.connectDatabase();
                 db.userPaymentDetails(paymentData,"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        adminPanelClose = new javax.swing.JLabel();
        adminPanelMin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        userPlanSearchValue = new javax.swing.JTextField();
        adminListSearch = new javax.swing.JButton();
        userListBack = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        paymentData = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        paymentId = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        paymentCodeSend = new javax.swing.JButton();
        paymentCodeGen = new javax.swing.JButton();
        paymentCode = new javax.swing.JTextField();
        userListDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setForeground(new java.awt.Color(0, 102, 255));

        adminPanelClose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        adminPanelClose.setForeground(new java.awt.Color(255, 255, 255));
        adminPanelClose.setText("X");
        adminPanelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminPanelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminPanelCloseMouseClicked(evt);
            }
        });

        adminPanelMin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        adminPanelMin.setForeground(new java.awt.Color(255, 255, 255));
        adminPanelMin.setText("_");
        adminPanelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminPanelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminPanelMinMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/movie/tv/show/images/i.png"))); // NOI18N
        jLabel1.setText("Tube");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(462, 462, 462)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(adminPanelMin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminPanelClose)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(adminPanelClose))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(adminPanelMin)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        userPlanSearchValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userPlanSearchValue.setToolTipText("");
        userPlanSearchValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                userPlanSearchValueKeyTyped(evt);
            }
        });

        adminListSearch.setBackground(new java.awt.Color(0, 0, 0));
        adminListSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        adminListSearch.setForeground(new java.awt.Color(255, 255, 255));
        adminListSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/movie/tv/show/images/search.png"))); // NOI18N
        adminListSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminListSearchActionPerformed(evt);
            }
        });

        userListBack.setBackground(new java.awt.Color(255, 255, 255));
        userListBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        userListBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/movie/tv/show/images/back.png"))); // NOI18N
        userListBack.setText("Back");
        userListBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userListBackActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(102, 102, 102));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("(User Payment List)");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        paymentData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "DateTime", "EndTime", "Amount", "Account No", "Trx Id", "Email", "code"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        paymentData.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        paymentData.setGridColor(new java.awt.Color(255, 255, 255));
        paymentData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paymentDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(paymentData);
        if (paymentData.getColumnModel().getColumnCount() > 0) {
            paymentData.getColumnModel().getColumn(1).setPreferredWidth(100);
            paymentData.getColumnModel().getColumn(2).setPreferredWidth(200);
            paymentData.getColumnModel().getColumn(3).setPreferredWidth(200);
            paymentData.getColumnModel().getColumn(4).setPreferredWidth(60);
            paymentData.getColumnModel().getColumn(5).setPreferredWidth(150);
            paymentData.getColumnModel().getColumn(6).setPreferredWidth(200);
            paymentData.getColumnModel().getColumn(7).setPreferredWidth(200);
            paymentData.getColumnModel().getColumn(8).setPreferredWidth(300);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Code:");

        paymentId.setEditable(false);
        paymentId.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("ID:");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Manage Details");

        paymentCodeSend.setBackground(new java.awt.Color(51, 51, 51));
        paymentCodeSend.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        paymentCodeSend.setForeground(new java.awt.Color(255, 255, 255));
        paymentCodeSend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/movie/tv/show/images/send.png"))); // NOI18N
        paymentCodeSend.setText("Send");
        paymentCodeSend.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        paymentCodeSend.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        paymentCodeSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentCodeSendActionPerformed(evt);
            }
        });

        paymentCodeGen.setBackground(new java.awt.Color(0, 153, 0));
        paymentCodeGen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        paymentCodeGen.setForeground(new java.awt.Color(255, 255, 255));
        paymentCodeGen.setText("Generate");
        paymentCodeGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentCodeGenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel23)
                            .addComponent(jLabel29)
                            .addComponent(paymentId, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                            .addComponent(jLabel28)
                            .addComponent(paymentCodeGen, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(paymentCode))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(paymentCodeSend, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paymentId, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paymentCode, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(paymentCodeGen)
                .addGap(43, 43, 43)
                .addComponent(paymentCodeSend)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        userListDelete.setBackground(new java.awt.Color(255, 255, 255));
        userListDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        userListDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/movie/tv/show/images/delete.png"))); // NOI18N
        userListDelete.setText("Delete");
        userListDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userListDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(userPlanSearchValue, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(adminListSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(userListDelete)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userListBack, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userPlanSearchValue, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adminListSearch)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)))
                .addGap(13, 13, 13)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userListDelete)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(userListBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminPanelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminPanelMinMouseClicked
         this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_adminPanelMinMouseClicked

    private void adminPanelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminPanelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_adminPanelCloseMouseClicked

    private void paymentCodeSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentCodeSendActionPerformed
          
        String uPaymentID,uPaymentCode;
       uPaymentID=paymentId.getText();
       uPaymentCode=paymentCode.getText();

        
        if (uPaymentID.equals("") || uPaymentCode.equals("") ) {
            JOptionPane.showMessageDialog(this, "Please select a field to update data");
        }else{
           
            
                   AdminDatabaseHandler db = new AdminDatabaseHandler();
                    db.connectDatabase(); 
                    boolean x= db.userPaymentCodeSend(Integer.valueOf(uPaymentID), uPaymentCode);
                    if (x) {
                JOptionPane.showMessageDialog(this, "Verification Code Send");
            }else{
                    JOptionPane.showMessageDialog(this, "Verification Code not Send");
                    }
                     
                     
//                     //After data updated table will be refreshed
//                       db.userPaymentDetails(paymentData, "");
//                paymentData.setModel(new DefaultTableModel(null, new Object[]{"ID","Name","Amount","Time","Date","Account No","Trx Id","Email"}));
//                 db.userPaymentDetails(paymentData, userPlanSearchValue.getText());
//                  paymentId.setText("");

 
        }
    }//GEN-LAST:event_paymentCodeSendActionPerformed

    private void adminListSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminListSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminListSearchActionPerformed

    private void userListBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userListBackActionPerformed
        
         AdminSettings settings = new AdminSettings();
            settings.setVisible(true);
            settings.pack();
            settings.setLocationRelativeTo(null);
            settings.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
    }//GEN-LAST:event_userListBackActionPerformed

    private void userListDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userListDeleteActionPerformed
        
        if (paymentId.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please Select a Row First");
        }else{
         AdminDatabaseHandler db=new AdminDatabaseHandler();
                    db.connectDatabase(); 
                     db.userPaymentDetailsDelete(Integer.valueOf(paymentId.getText()));
                     JOptionPane.showMessageDialog(this, "Payment Details Deleted");
                     
                     //After data updated table will be refreshed
//                        this.setVisible(false); //this will close frame i.e. NewJFrame
//                        new UserList().setVisible(true);
                db.userPaymentDetails(paymentData, "");
                paymentData.setModel(new DefaultTableModel(null, new Object[]{"ID","Name","DateTime","EndTime","Amount","Account No","Trx Id","Email"}));
                 db.userPaymentDetails(paymentData, userPlanSearchValue.getText());
                 paymentId.setText("");
                 
    }
        
    }//GEN-LAST:event_userListDeleteActionPerformed

    private void paymentDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paymentDataMouseClicked
        int rowIndex=paymentData.getSelectedRow();
        
        DefaultTableModel model = (DefaultTableModel) paymentData.getModel();
        //Date date;
        
        paymentId.setText(model.getValueAt(rowIndex, 0).toString());
        //java.sql.Timestamp ourJavaDateObject = new java.sql.Timestamp((long) model.getValueAt(rowIndex, 3));
       // userPaymentDateTime.setText(""+ourJavaDateObject);
      //  userPaymentAccountNo.setText(model.getValueAt(rowIndex, 4).toString());
      //  userPaymentTrxId.setText(model.getValueAt(rowIndex, 5).toString());
        //userPaymentEmail.setText(model.getValueAt(rowIndex, 6).toString());
    }//GEN-LAST:event_paymentDataMouseClicked

    private void userPlanSearchValueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userPlanSearchValueKeyTyped
         AdminDatabaseHandler db=new AdminDatabaseHandler();
                 db.connectDatabase();
                 paymentData.setModel(new DefaultTableModel(null, new Object[]{"ID","Name","DateTime","EndTime","Amount","Account No","Trx Id","Email"}));
                 db.userPaymentDetails(paymentData, userPlanSearchValue.getText());
    }//GEN-LAST:event_userPlanSearchValueKeyTyped

    private void paymentCodeGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentCodeGenActionPerformed
        //A class that represents an immutable universally unique identifier (UUID). A UUID represents a 128-bit value.
        String uuid = UUID.randomUUID().toString();
         
       paymentCode.setText(uuid.replace("-", ""));
    }//GEN-LAST:event_paymentCodeGenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminListSearch;
    private javax.swing.JLabel adminPanelClose;
    private javax.swing.JLabel adminPanelMin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField paymentCode;
    private javax.swing.JButton paymentCodeGen;
    private javax.swing.JButton paymentCodeSend;
    private javax.swing.JTable paymentData;
    private javax.swing.JTextField paymentId;
    private javax.swing.JButton userListBack;
    private javax.swing.JButton userListDelete;
    private javax.swing.JTextField userPlanSearchValue;
    // End of variables declaration//GEN-END:variables
}
