/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package online.movie.tv.show;

import java.sql.ResultSet;
import javax.swing.JFrame;

/**
 *
 * @author user
 */
public class SearchResults extends javax.swing.JFrame {
    ResultSet results;
    int Id1, Id2, Id3, Id4, Id5, Id6, Id7, Id8;
    ContentDatabaseHandler db;
    /**
     * Creates new form SearchResults
     */
    public SearchResults(String query) {
        initComponents();
        LookAndFeel();
        setResizable(false);
        setLocationRelativeTo(null);
        setVisible(true);
         this.pack();
        db = new ContentDatabaseHandler();
        db.connectDatabase();
        
        results = db.getContent(query);
        
        try{
            int i=0;
            while(results.next()){
                String name = results.getString("name");
                int id = results.getInt("id");
                
                
                switch(i){
                    case 0:Result1.setText(name);
                        Id1 = id;
                        break;
                    case 1:Result2.setText(name);
                        Id2 = id;
                        break;
                    case 2:Result3.setText(name);
                        Id3 = id;
                        break;
                    case 3:Result4.setText(name);
                        Id4 = id;
                        break;
                    case 4:Result5.setText(name);
                        Id5 = id;
                        break;
                    case 5:Result6.setText(name);
                        Id6 = id;
                        break;
                    case 6:Result7.setText(name);
                        Id7 = id;
                        break;
                    case 7:Result8.setText(name);
                        Id8 = id;
                        break;
                }
                i++;
            }
            if(i<1)Result1.setVisible(false);
            if(i<2)Result2.setVisible(false);
            if(i<3)Result3.setVisible(false);
            if(i<4)Result4.setVisible(false);
            if(i<5)Result5.setVisible(false);
            if(i<6)Result6.setVisible(false);
            if(i<7)Result7.setVisible(false);
            if(i<8)Result8.setVisible(false);
        }catch(Exception e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TopSectionSearchPage = new javax.swing.JPanel();
        HomeButton = new javax.swing.JButton();
        GoButton = new javax.swing.JButton();
        SearchBar = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        Result1 = new javax.swing.JButton();
        Result5 = new javax.swing.JButton();
        Result2 = new javax.swing.JButton();
        Result6 = new javax.swing.JButton();
        Result3 = new javax.swing.JButton();
        Result7 = new javax.swing.JButton();
        Result4 = new javax.swing.JButton();
        Result8 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        adminPanelClose4 = new javax.swing.JLabel();
        adminPanelMin4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        TopSectionSearchPage.setBackground(new java.awt.Color(51, 153, 0));
        TopSectionSearchPage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        HomeButton.setBackground(new java.awt.Color(0, 102, 255));
        HomeButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        HomeButton.setText("Home");
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });

        GoButton.setBackground(new java.awt.Color(0, 102, 255));
        GoButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        GoButton.setText("Go");
        GoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoButtonActionPerformed(evt);
            }
        });

        SearchBar.setText("Search");

        javax.swing.GroupLayout TopSectionSearchPageLayout = new javax.swing.GroupLayout(TopSectionSearchPage);
        TopSectionSearchPage.setLayout(TopSectionSearchPageLayout);
        TopSectionSearchPageLayout.setHorizontalGroup(
            TopSectionSearchPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopSectionSearchPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 452, Short.MAX_VALUE)
                .addComponent(SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        TopSectionSearchPageLayout.setVerticalGroup(
            TopSectionSearchPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopSectionSearchPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TopSectionSearchPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HomeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SearchBar))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        Result1.setBackground(new java.awt.Color(51, 51, 51));
        Result1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Result1.setForeground(new java.awt.Color(255, 255, 255));
        Result1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Result1ActionPerformed(evt);
            }
        });

        Result5.setBackground(new java.awt.Color(51, 51, 51));
        Result5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Result5.setForeground(new java.awt.Color(255, 255, 255));
        Result5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Result5ActionPerformed(evt);
            }
        });

        Result2.setBackground(new java.awt.Color(51, 51, 51));
        Result2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Result2.setForeground(new java.awt.Color(255, 255, 255));
        Result2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Result2ActionPerformed(evt);
            }
        });

        Result6.setBackground(new java.awt.Color(51, 51, 51));
        Result6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Result6.setForeground(new java.awt.Color(255, 255, 255));
        Result6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Result6ActionPerformed(evt);
            }
        });

        Result3.setBackground(new java.awt.Color(51, 51, 51));
        Result3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Result3.setForeground(new java.awt.Color(255, 255, 255));
        Result3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Result3ActionPerformed(evt);
            }
        });

        Result7.setBackground(new java.awt.Color(51, 51, 51));
        Result7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Result7.setForeground(new java.awt.Color(255, 255, 255));
        Result7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Result7ActionPerformed(evt);
            }
        });

        Result4.setBackground(new java.awt.Color(51, 51, 51));
        Result4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Result4.setForeground(new java.awt.Color(255, 255, 255));
        Result4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Result4ActionPerformed(evt);
            }
        });

        Result8.setBackground(new java.awt.Color(51, 51, 51));
        Result8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Result8.setForeground(new java.awt.Color(255, 255, 255));
        Result8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Result8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Result1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(Result5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Result2, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(Result6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Result3, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(Result7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Result4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Result8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Result1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(Result2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Result3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Result4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Result5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Result7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Result8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Result6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 102, 255));
        jPanel6.setForeground(new java.awt.Color(0, 102, 255));

        adminPanelClose4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        adminPanelClose4.setForeground(new java.awt.Color(255, 255, 255));
        adminPanelClose4.setText("X");
        adminPanelClose4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminPanelClose4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminPanelClose4MouseClicked(evt);
            }
        });

        adminPanelMin4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        adminPanelMin4.setForeground(new java.awt.Color(255, 255, 255));
        adminPanelMin4.setText("_");
        adminPanelMin4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminPanelMin4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminPanelMin4MouseClicked(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(102, 102, 102));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/movie/tv/show/images/i.png"))); // NOI18N
        jLabel10.setText("Tube");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(409, 409, 409)
                .addComponent(adminPanelMin4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminPanelClose4)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(adminPanelMin4)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminPanelClose4)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TopSectionSearchPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TopSectionSearchPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        HomePage h = new HomePage();
        h.setVisible(true);
         this.pack();
        this.dispose();
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void Result2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Result2ActionPerformed
        String query = "SELECT content_type FROM content WHERE id="+Id2;
        ResultSet content = db.getContent(query);
        String content_type = null;
        try{
            while(content.next()){
                content_type = content.getString("content_type");
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        if(content_type.equals("movie")){
            MoviePage m = new MoviePage(Id2);
            m.setVisible(true);
        }
        else if(content_type.equals("tv_series")){
            TVPage t = new TVPage(Id2);
            t.setVisible(true);
        }
        if(content_type.length()>0)this.dispose();
    }//GEN-LAST:event_Result2ActionPerformed

    private void Result1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Result1ActionPerformed
        String query = "SELECT content_type FROM content WHERE id="+Id1;
        ResultSet content = db.getContent(query);
        String content_type = null;
        try{
            while(content.next()){
                content_type = content.getString("content_type");
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        if(content_type.equals("movie")){
            MoviePage m = new MoviePage(Id1);
            m.setVisible(true);
        }
        else if(content_type.equals("tv_series")){
            TVPage t = new TVPage(Id1);
            t.setVisible(true);
        }
        if(content_type.length()>0)this.dispose();
    }//GEN-LAST:event_Result1ActionPerformed

    private void Result3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Result3ActionPerformed
        String query = "SELECT content_type FROM content WHERE id="+Id3;
        ResultSet content = db.getContent(query);
        String content_type = null;
        try{
            while(content.next()){
                content_type = content.getString("content_type");
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        if(content_type.equals("movie")){
            MoviePage m = new MoviePage(Id3);
            m.setVisible(true);
        }
        else if(content_type.equals("tv_series")){
            TVPage t = new TVPage(Id3);
            t.setVisible(true);
        }
        if(content_type.length()>0)this.dispose();
    }//GEN-LAST:event_Result3ActionPerformed

    private void Result5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Result5ActionPerformed
        String query = "SELECT content_type FROM content WHERE id="+Id5;
        ResultSet content = db.getContent(query);
        String content_type = null;
        try{
            while(content.next()){
                content_type = content.getString("content_type");
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        if(content_type.equals("movie")){
            MoviePage m = new MoviePage(Id8);
            m.setVisible(true);
        }
        else if(content_type.equals("tv_series")){
            TVPage t = new TVPage(Id8);
            t.setVisible(true);
        }
        if(content_type.length()>0)this.dispose();
    }//GEN-LAST:event_Result5ActionPerformed

    private void Result4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Result4ActionPerformed
        String query = "SELECT content_type FROM content WHERE id="+Id4;
        ResultSet content = db.getContent(query);
        String content_type = null;
        try{
            while(content.next()){
                content_type = content.getString("content_type");
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        if(content_type.equals("movie")){
            MoviePage m = new MoviePage(Id4);
            m.setVisible(true);
        }
        else if(content_type.equals("tv_series")){
            TVPage t = new TVPage(Id4);
            t.setVisible(true);
        }
        if(content_type.length()>0)this.dispose();
    }//GEN-LAST:event_Result4ActionPerformed

    private void Result6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Result6ActionPerformed
        String query = "SELECT content_type FROM content WHERE id="+Id6;
        ResultSet content = db.getContent(query);
        String content_type = null;
        try{
            while(content.next()){
                content_type = content.getString("content_type");
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        if(content_type.equals("movie")){
            MoviePage m = new MoviePage(Id6);
            m.setVisible(true);
        }
        else if(content_type.equals("tv_series")){
            TVPage t = new TVPage(Id6);
            t.setVisible(true);
        }
        if(content_type.length()>0)this.dispose();
    }//GEN-LAST:event_Result6ActionPerformed

    private void Result7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Result7ActionPerformed
        String query = "SELECT content_type FROM content WHERE id="+Id7;
        ResultSet content = db.getContent(query);
        String content_type = null;
        try{
            while(content.next()){
                content_type = content.getString("content_type");
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        if(content_type.equals("movie")){
            MoviePage m = new MoviePage(Id7);
            m.setVisible(true);
        }
        else if(content_type.equals("tv_series")){
            TVPage t = new TVPage(Id7);
            t.setVisible(true);
        }
        if(content_type.length()>0)this.dispose();
    }//GEN-LAST:event_Result7ActionPerformed

    private void Result8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Result8ActionPerformed
        String query = "SELECT content_type FROM content WHERE id="+Id8;
        ResultSet content = db.getContent(query);
        String content_type = null;
        try{
            while(content.next()){
                content_type = content.getString("content_type");
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        if(content_type.equals("movie")){
            MoviePage m = new MoviePage(Id8);
            m.setVisible(true);
        }
        else if(content_type.equals("tv_series")){
            TVPage t = new TVPage(Id8);
            t.setVisible(true);
        }
        if(content_type.length()>0)this.dispose();
    }//GEN-LAST:event_Result8ActionPerformed

    private void GoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoButtonActionPerformed
        String query = "SELECT * FROM CONTENT WHERE name LIKE %"+SearchBar.getText().toString()+"%";
        SearchResults s = new SearchResults(query);
        s.setVisible(true);
        this.pack();
        this.dispose();
    }//GEN-LAST:event_GoButtonActionPerformed

    private void adminPanelClose4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminPanelClose4MouseClicked
        System.exit(0);
    }//GEN-LAST:event_adminPanelClose4MouseClicked

    private void adminPanelMin4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminPanelMin4MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_adminPanelMin4MouseClicked

    /**
     * @param args the command line arguments
     */
    public void LookAndFeel(){
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GoButton;
    private javax.swing.JButton HomeButton;
    private javax.swing.JButton Result1;
    private javax.swing.JButton Result2;
    private javax.swing.JButton Result3;
    private javax.swing.JButton Result4;
    private javax.swing.JButton Result5;
    private javax.swing.JButton Result6;
    private javax.swing.JButton Result7;
    private javax.swing.JButton Result8;
    private javax.swing.JTextField SearchBar;
    private javax.swing.JPanel TopSectionSearchPage;
    private javax.swing.JLabel adminPanelClose;
    private javax.swing.JLabel adminPanelClose1;
    private javax.swing.JLabel adminPanelClose2;
    private javax.swing.JLabel adminPanelClose3;
    private javax.swing.JLabel adminPanelClose4;
    private javax.swing.JLabel adminPanelMin;
    private javax.swing.JLabel adminPanelMin1;
    private javax.swing.JLabel adminPanelMin2;
    private javax.swing.JLabel adminPanelMin3;
    private javax.swing.JLabel adminPanelMin4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
