/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package online.movie.tv.show;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.InputStream;
import java.sql.ResultSet;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author user
 */
public class TVPage extends javax.swing.JFrame {
    ContentDatabaseHandler db;
    ResultSet info;
    int id_content, id_tv, id_season;
    /**
     * Creates new form TVPage
     */
    public TVPage(int id) {
        initComponents();
        LookAndFeel();
        setResizable(false);
        setLocationRelativeTo(null);
        setVisible(true);
        id_content = id;
        
        db = new ContentDatabaseHandler();
        db.connectDatabase();
        
        String query = "SELECT * FROM content WHERE id="+id_content;
        info = db.getContent(query);
        
        try{
            while(info.next()){
                java.sql.Blob img = info.getBlob("covers");
                InputStream in = img.getBinaryStream();  
                BufferedImage image = ImageIO.read(in);
                
                Image imge = image.getScaledInstance(tvSeriesCover.getWidth(), tvSeriesCover.getHeight(), Image.SCALE_SMOOTH);
                        ImageIcon image1 = new ImageIcon(imge);
                        tvSeriesCover.setIcon(image1);
                
                String name = info.getString("name");
                SeriesTitleLabel.setText(name);
                
                String language = info.getString("language");
                LanguageLabel.setText(language);
                
                String genre = info.getString("genre");
                GenreLabel.setText(genre);
                
                String release_date = info.getString("release_date");
                ReleaseDateLabel.setText(release_date);
                
                String cast = "Starring:\n"+info.getString("cast");
                CastTextArea.setText(cast);
                
                String synopsis = "Synopsis:\n"+info.getString("synopsis");
                SynopsisTextArea.setText(synopsis);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        
        query = "SELECT tv_series_id FROM content_tv WHERE content_id="+id_content;
        info = db.getContent(query);
        
        try{
            while(info.next()){
                id_tv = info.getInt("tv_series_id");
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        
        query = "SELECT name FROM content_tv_seasons WHERE tv_series_id="+id_tv;
        info = db.getContent(query);
        
        try{
            while(info.next()){
                String season = info.getString("name");
                SeasonSelect.addItem(season);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        
        String DefaultSeason = SeasonSelect.getItemAt(0).toString();
        
        query = "SELECT id FROM content_tv_seasons WHERE tv_series_id="+id_tv+" AND name='"+DefaultSeason+"'";
        info = db.getContent(query);
        
        try{
            while(info.next()){
                id_season = info.getInt("id");
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        
        query = "SELECT name FROM content_tv_episode WHERE tv_season_id="+id_season;
        info = db.getContent(query);
        
        try{
            while(info.next()){
                String episode = info.getString("name");
                EpisodeSelect.addItem(episode);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        HomeButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        PlayButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        SynopsisTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        CastTextArea = new javax.swing.JTextArea();
        ReleaseDateLabel = new javax.swing.JLabel();
        GenreLabel = new javax.swing.JLabel();
        LanguageLabel = new javax.swing.JLabel();
        SeasonSelect = new javax.swing.JComboBox<>();
        EpisodeSelect = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        ShowrunnerTextArea = new javax.swing.JTextArea();
        SeriesTitleLabel = new javax.swing.JLabel();
        tvSeriesCover = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        adminPanelClose3 = new javax.swing.JLabel();
        adminPanelMin3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 153, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        HomeButton.setBackground(new java.awt.Color(0, 102, 204));
        HomeButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        HomeButton.setText("Home");
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HomeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        PlayButton.setBackground(new java.awt.Color(204, 0, 0));
        PlayButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PlayButton.setText("Play");

        SynopsisTextArea.setEditable(false);
        SynopsisTextArea.setColumns(20);
        SynopsisTextArea.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        SynopsisTextArea.setRows(5);
        SynopsisTextArea.setText("Synopsis");
        SynopsisTextArea.setAutoscrolls(false);
        SynopsisTextArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane1.setViewportView(SynopsisTextArea);

        CastTextArea.setEditable(false);
        CastTextArea.setColumns(15);
        CastTextArea.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        CastTextArea.setRows(3);
        CastTextArea.setText("Starring");
        CastTextArea.setAutoscrolls(false);
        CastTextArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane2.setViewportView(CastTextArea);

        ReleaseDateLabel.setBackground(new java.awt.Color(255, 255, 255));
        ReleaseDateLabel.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        ReleaseDateLabel.setText("Release Date");
        ReleaseDateLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        ReleaseDateLabel.setOpaque(true);

        GenreLabel.setBackground(new java.awt.Color(255, 255, 255));
        GenreLabel.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        GenreLabel.setText("Genre");
        GenreLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        GenreLabel.setOpaque(true);

        LanguageLabel.setBackground(new java.awt.Color(255, 255, 255));
        LanguageLabel.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        LanguageLabel.setText("Language");
        LanguageLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        LanguageLabel.setOpaque(true);

        SeasonSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        SeasonSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeasonSelectActionPerformed(evt);
            }
        });

        EpisodeSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));

        ShowrunnerTextArea.setEditable(false);
        ShowrunnerTextArea.setColumns(15);
        ShowrunnerTextArea.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        ShowrunnerTextArea.setRows(5);
        ShowrunnerTextArea.setText("Showrunner");
        ShowrunnerTextArea.setAutoscrolls(false);
        ShowrunnerTextArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane3.setViewportView(ShowrunnerTextArea);

        SeriesTitleLabel.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 36)); // NOI18N
        SeriesTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        SeriesTitleLabel.setText("Series Title");

        tvSeriesCover.setBackground(new java.awt.Color(255, 255, 255));
        tvSeriesCover.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tvSeriesCover.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SeriesTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(tvSeriesCover, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(ReleaseDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GenreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LanguageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SeasonSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EpisodeSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addComponent(PlayButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(SeriesTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tvSeriesCover, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ReleaseDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LanguageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(GenreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SeasonSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(EpisodeSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60)
                .addComponent(PlayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane4.setViewportView(jPanel3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(0, 102, 255));
        jPanel7.setForeground(new java.awt.Color(0, 102, 255));

        adminPanelClose3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        adminPanelClose3.setForeground(new java.awt.Color(255, 255, 255));
        adminPanelClose3.setText("X");
        adminPanelClose3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminPanelClose3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminPanelClose3MouseClicked(evt);
            }
        });

        adminPanelMin3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        adminPanelMin3.setForeground(new java.awt.Color(255, 255, 255));
        adminPanelMin3.setText("_");
        adminPanelMin3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminPanelMin3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminPanelMin3MouseClicked(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(102, 102, 102));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/movie/tv/show/images/i.png"))); // NOI18N
        jLabel9.setText("Tube");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(375, 375, 375)
                .addComponent(adminPanelMin3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminPanelClose3)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(adminPanelMin3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminPanelClose3)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        HomePage h = new HomePage();
        h.setVisible(true);
        h.pack();
        h.setLocationRelativeTo(null);
         h.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void SeasonSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeasonSelectActionPerformed
        /*EpisodeSelect.removeAllItems();
        
        db = new ContentDatabaseHandler();
        db.connectDatabase();
        
        String SeasonSelected = SeasonSelect.getSelectedItem().toString();
        
        String query = "SELECT id FROM content_tv_seasons WHERE tv_series_id="+id_tv+" AND name='"+SeasonSelected+"'";
        info = db.getContent(query);
        try{
            while(info.next()){
                id_season = info.getInt("id");
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        
        query = "SELECT name FROM content_tv_episode WHERE tv_season_id="+id_season;
        info = db.getContent(query);
        
        try{
            while(info.next()){
                String episode = info.getString("name");
                EpisodeSelect.addItem(episode);
            }
        }catch(Exception e){
            e.printStackTrace();
        }*/
    }//GEN-LAST:event_SeasonSelectActionPerformed

    private void adminPanelClose3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminPanelClose3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_adminPanelClose3MouseClicked

    private void adminPanelMin3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminPanelMin3MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_adminPanelMin3MouseClicked

    /**
     * @param args the command line arguments
     */
    public void LookAndFeel(){
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TVPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TVPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TVPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TVPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea CastTextArea;
    private javax.swing.JComboBox<String> EpisodeSelect;
    private javax.swing.JLabel GenreLabel;
    private javax.swing.JButton HomeButton;
    private javax.swing.JLabel LanguageLabel;
    private javax.swing.JButton PlayButton;
    private javax.swing.JLabel ReleaseDateLabel;
    private javax.swing.JComboBox<String> SeasonSelect;
    private javax.swing.JLabel SeriesTitleLabel;
    private javax.swing.JTextArea ShowrunnerTextArea;
    private javax.swing.JTextArea SynopsisTextArea;
    private javax.swing.JLabel adminPanelClose;
    private javax.swing.JLabel adminPanelClose1;
    private javax.swing.JLabel adminPanelClose2;
    private javax.swing.JLabel adminPanelClose3;
    private javax.swing.JLabel adminPanelMin;
    private javax.swing.JLabel adminPanelMin1;
    private javax.swing.JLabel adminPanelMin2;
    private javax.swing.JLabel adminPanelMin3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel tvSeriesCover;
    // End of variables declaration//GEN-END:variables
}
