/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package online.movie.tv.show;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Sagor Ahamed
 */
public class UpdatetvSeries extends javax.swing.JFrame {
    
    String coverFileName;
    File file;
    FileInputStream fileInputStream;
    int coverlength;
    /**
     * Creates new form AdminPanel
     */
    public UpdatetvSeries() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        updateTvId.setText(ViewTvSeriesPost.tvSeriesModel.getValueAt(ViewTvSeriesPost.tvRowIndex, 0).toString());
        updateTvTitle.setText(ViewTvSeriesPost.tvSeriesModel.getValueAt(ViewTvSeriesPost.tvRowIndex, 1).toString());
        updateTvGenre.setText(ViewTvSeriesPost.tvSeriesModel.getValueAt(ViewTvSeriesPost.tvRowIndex, 2).toString());
        updateTvLanguage.setText(ViewTvSeriesPost.tvSeriesModel.getValueAt(ViewTvSeriesPost.tvRowIndex, 3).toString());
        updateTvCast.setText(ViewTvSeriesPost.tvSeriesModel.getValueAt(ViewTvSeriesPost.tvRowIndex, 4).toString());
        updateTvSynopsis.setText(ViewTvSeriesPost.tvSeriesModel.getValueAt(ViewTvSeriesPost.tvRowIndex, 5).toString());
        updateTvRating.setText(ViewTvSeriesPost.tvSeriesModel.getValueAt(ViewTvSeriesPost.tvRowIndex, 6).toString());
        //ViewTvSeriesPost.tvSeriesModel.getValueAt(ViewTvSeriesPost.tvRowIndex, 7).toString()
        
        ImageIcon imageIcon = new ImageIcon(AdminDatabaseHandler.tvSeriesImg);
        Image image = imageIcon.getImage().getScaledInstance(updateTvCoverImg.getWidth(), updateTvCoverImg.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image2 = new ImageIcon(image);
        updateTvCoverImg.setIcon(image2);
        
        udateTvIframeLink.setText(ViewTvSeriesPost.tvSeriesModel.getValueAt(ViewTvSeriesPost.tvRowIndex, 8).toString());
        updateTvReleaseDate.setText(ViewTvSeriesPost.tvSeriesModel.getValueAt(ViewTvSeriesPost.tvRowIndex, 9).toString());
        updateTvContentType.setText(ViewTvSeriesPost.tvSeriesModel.getValueAt(ViewTvSeriesPost.tvRowIndex, 10).toString());
        updateTvSeriesId.setText(ViewTvSeriesPost.tvSeriesModel.getValueAt(ViewTvSeriesPost.tvRowIndex, 11).toString());
        updateTvNoSeason.setText(ViewTvSeriesPost.tvSeriesModel.getValueAt(ViewTvSeriesPost.tvRowIndex, 12).toString());
        updateTvShowRunner.setText(ViewTvSeriesPost.tvSeriesModel.getValueAt(ViewTvSeriesPost.tvRowIndex, 13).toString());
        updateTvSeasonId.setText(ViewTvSeriesPost.tvSeriesModel.getValueAt(ViewTvSeriesPost.tvRowIndex, 14).toString());
        updateSeasonName.setText(ViewTvSeriesPost.tvSeriesModel.getValueAt(ViewTvSeriesPost.tvRowIndex, 15).toString());
        updateTvNoEpisode.setText(ViewTvSeriesPost.tvSeriesModel.getValueAt(ViewTvSeriesPost.tvRowIndex, 16).toString());
        updateTvEpisodeId.setText(ViewTvSeriesPost.tvSeriesModel.getValueAt(ViewTvSeriesPost.tvRowIndex, 17).toString());
        updateEpisodeName.setText(ViewTvSeriesPost.tvSeriesModel.getValueAt(ViewTvSeriesPost.tvRowIndex, 18).toString());
        updateTvRuntime.setText(ViewTvSeriesPost.tvSeriesModel.getValueAt(ViewTvSeriesPost.tvRowIndex, 19).toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        adminPanelClose = new javax.swing.JLabel();
        adminPanelMin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        updateTvBack = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        updateTvSeries = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        udateTvIframeLink = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        updateTvLanguage = new javax.swing.JTextField();
        updateTvRuntime = new javax.swing.JTextField();
        updateTvId = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        updateTvCoverBrowse = new javax.swing.JButton();
        updateTvCoverImg = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        updateTvReleaseDate = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        updateTvGenre = new javax.swing.JTextField();
        updateTvCast = new javax.swing.JTextField();
        updateTvShowRunner = new javax.swing.JTextField();
        updateTvRating = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        updateTvSynopsis = new javax.swing.JTextArea();
        updateTvTitle = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        updateEpisodeName = new javax.swing.JTextField();
        updateTvContentType = new javax.swing.JTextField();
        updateTvNoEpisode = new javax.swing.JTextField();
        updateTvSeasonId = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        updateTvNoSeason = new javax.swing.JTextField();
        updateTvEpisodeId = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        updateSeasonName = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        updateTvSeriesId = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setForeground(new java.awt.Color(0, 102, 255));

        adminPanelClose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        adminPanelClose.setForeground(new java.awt.Color(255, 255, 255));
        adminPanelClose.setText("X");
        adminPanelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminPanelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminPanelCloseMouseClicked(evt);
            }
        });

        adminPanelMin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        adminPanelMin.setForeground(new java.awt.Color(255, 255, 255));
        adminPanelMin.setText("_");
        adminPanelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminPanelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminPanelMinMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/movie/tv/show/images/i.png"))); // NOI18N
        jLabel1.setText("Tube");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(345, 345, 345)
                .addComponent(adminPanelMin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminPanelClose)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(adminPanelClose))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(adminPanelMin)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        updateTvBack.setBackground(new java.awt.Color(255, 255, 255));
        updateTvBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updateTvBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/movie/tv/show/images/back.png"))); // NOI18N
        updateTvBack.setText("Back");
        updateTvBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTvBackActionPerformed(evt);
            }
        });

        updateTvSeries.setBackground(new java.awt.Color(255, 255, 255));
        updateTvSeries.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updateTvSeries.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/movie/tv/show/images/Update.png"))); // NOI18N
        updateTvSeries.setText("Update");
        updateTvSeries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTvSeriesActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(102, 102, 102));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Update Tv Series");

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel12.setBackground(new java.awt.Color(102, 102, 102));
        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Cast:");

        udateTvIframeLink.setColumns(20);
        udateTvIframeLink.setRows(5);
        jScrollPane1.setViewportView(udateTvIframeLink);

        jLabel10.setBackground(new java.awt.Color(102, 102, 102));
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Language:");

        jLabel15.setBackground(new java.awt.Color(102, 102, 102));
        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Show Runner:");

        updateTvLanguage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateTvLanguage.setToolTipText("");

        updateTvRuntime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateTvRuntime.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                updateTvRuntimeFocusLost(evt);
            }
        });
        updateTvRuntime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                updateTvRuntimeKeyPressed(evt);
            }
        });

        updateTvId.setEditable(false);
        updateTvId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateTvId.setToolTipText("");

        jLabel18.setBackground(new java.awt.Color(102, 102, 102));
        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("video:");

        jLabel17.setBackground(new java.awt.Color(102, 102, 102));
        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("cover:");

        updateTvCoverBrowse.setBackground(new java.awt.Color(0, 153, 0));
        updateTvCoverBrowse.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updateTvCoverBrowse.setText("Browse");
        updateTvCoverBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTvCoverBrowseActionPerformed(evt);
            }
        });

        updateTvCoverImg.setBackground(new java.awt.Color(255, 255, 255));
        updateTvCoverImg.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel19.setBackground(new java.awt.Color(102, 102, 102));
        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("writers:");

        jLabel9.setBackground(new java.awt.Color(102, 102, 102));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Content Type:");

        updateTvReleaseDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateTvReleaseDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                updateTvReleaseDateKeyPressed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(102, 102, 102));
        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Rating:");

        jLabel11.setBackground(new java.awt.Color(102, 102, 102));
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Synopsis:");

        jLabel16.setBackground(new java.awt.Color(102, 102, 102));
        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Runtime:");

        jLabel7.setBackground(new java.awt.Color(102, 102, 102));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Title:");

        updateTvGenre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateTvGenre.setToolTipText("");

        updateTvCast.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateTvCast.setToolTipText("");

        updateTvShowRunner.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        updateTvRating.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateTvRating.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                updateTvRatingFocusLost(evt);
            }
        });
        updateTvRating.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                updateTvRatingKeyPressed(evt);
            }
        });

        updateTvSynopsis.setColumns(20);
        updateTvSynopsis.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        updateTvSynopsis.setRows(5);
        updateTvSynopsis.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane2.setViewportView(updateTvSynopsis);

        updateTvTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateTvTitle.setToolTipText("");

        jLabel13.setBackground(new java.awt.Color(102, 102, 102));
        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Genre:");

        jLabel20.setBackground(new java.awt.Color(102, 102, 102));
        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("ID:");

        updateEpisodeName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateEpisodeName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                updateEpisodeNameFocusLost(evt);
            }
        });
        updateEpisodeName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                updateEpisodeNameKeyPressed(evt);
            }
        });

        updateTvContentType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateTvContentType.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                updateTvContentTypeFocusLost(evt);
            }
        });
        updateTvContentType.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                updateTvContentTypeKeyPressed(evt);
            }
        });

        updateTvNoEpisode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateTvNoEpisode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                updateTvNoEpisodeFocusLost(evt);
            }
        });
        updateTvNoEpisode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                updateTvNoEpisodeKeyPressed(evt);
            }
        });

        updateTvSeasonId.setEditable(false);
        updateTvSeasonId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateTvSeasonId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                updateTvSeasonIdFocusLost(evt);
            }
        });
        updateTvSeasonId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                updateTvSeasonIdKeyPressed(evt);
            }
        });

        jLabel21.setBackground(new java.awt.Color(102, 102, 102));
        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("No Of Episode:");

        jLabel22.setBackground(new java.awt.Color(102, 102, 102));
        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Season Id:");

        updateTvNoSeason.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateTvNoSeason.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                updateTvNoSeasonFocusLost(evt);
            }
        });
        updateTvNoSeason.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                updateTvNoSeasonKeyPressed(evt);
            }
        });

        updateTvEpisodeId.setEditable(false);
        updateTvEpisodeId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateTvEpisodeId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                updateTvEpisodeIdFocusLost(evt);
            }
        });
        updateTvEpisodeId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                updateTvEpisodeIdKeyPressed(evt);
            }
        });

        jLabel23.setBackground(new java.awt.Color(102, 102, 102));
        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Episode Id:");

        jLabel24.setBackground(new java.awt.Color(102, 102, 102));
        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("No Of Season:");

        updateSeasonName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateSeasonName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                updateSeasonNameFocusLost(evt);
            }
        });
        updateSeasonName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                updateSeasonNameKeyPressed(evt);
            }
        });

        jLabel25.setBackground(new java.awt.Color(102, 102, 102));
        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Episode Name:");

        jLabel26.setBackground(new java.awt.Color(102, 102, 102));
        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Season Name:");

        updateTvSeriesId.setEditable(false);
        updateTvSeriesId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateTvSeriesId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                updateTvSeriesIdFocusLost(evt);
            }
        });
        updateTvSeriesId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                updateTvSeriesIdKeyPressed(evt);
            }
        });

        jLabel27.setBackground(new java.awt.Color(102, 102, 102));
        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Tv Series Id:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(647, 647, 647))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(updateTvLanguage)
                                            .addComponent(updateTvCast)
                                            .addComponent(updateTvRating)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(updateTvShowRunner, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel16)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(updateTvReleaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(updateTvCoverBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(updateTvCoverImg, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(updateTvRuntime)
                                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jScrollPane2)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(updateTvId, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(updateTvTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(updateTvGenre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(updateTvSeasonId, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(updateTvEpisodeId, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(updateTvNoSeason, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(113, 113, 113)
                                            .addComponent(jLabel21)
                                            .addGap(18, 18, 18)
                                            .addComponent(updateTvNoEpisode, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(updateSeasonName, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel25)
                                            .addGap(18, 18, 18)
                                            .addComponent(updateEpisodeName, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(updateTvContentType, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(jLabel27)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(updateTvSeriesId, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateTvId, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateTvTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateTvGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateTvLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateTvCast, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(updateTvSeriesId, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel27))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(updateTvEpisodeId, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23))
                                .addGap(14, 14, 14)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(updateTvNoSeason, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(updateTvNoEpisode, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel24))
                                .addGap(18, 18, 18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(updateTvContentType, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(updateTvSeasonId, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(207, 207, 207)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(updateEpisodeName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25))
                    .addComponent(updateSeasonName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(updateTvRating, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(9, 9, 9)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel17)
                                .addComponent(updateTvCoverBrowse)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(updateTvCoverImg, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updateTvReleaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(updateTvRuntime, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(updateTvShowRunner, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jScrollPane4.setViewportView(jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator1)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(updateTvSeries)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(updateTvBack, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(updateTvBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateTvSeries, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminPanelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminPanelMinMouseClicked
         this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_adminPanelMinMouseClicked

    private void adminPanelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminPanelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_adminPanelCloseMouseClicked

    private void updateTvBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTvBackActionPerformed
            ViewTvSeriesPost tvSeriesPost = new ViewTvSeriesPost();
            tvSeriesPost.setVisible(true);
            tvSeriesPost.pack();
            tvSeriesPost.setLocationRelativeTo(null);
            tvSeriesPost.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
    }//GEN-LAST:event_updateTvBackActionPerformed

    private void updateTvSeriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTvSeriesActionPerformed
        String mTitle,mGenre,mLanguage,mCast,mSynopsis,iframeLink,mContentType,
                mDirectedBy,mCover,tvShowRunner,tvSeasonName,tvEpisodeName ;
        int mRuntime,mID,tvSeriesId,noOfSeasons,tvSeasonId,tvNoOfEpisode,tvEpisodeId,tvReleaseDate;
        Double mRating;
        
        mContentType=updateTvContentType.getText();
        mID=Integer.valueOf(updateTvId.getText());
        mTitle=updateTvTitle.getText();
        mGenre=updateTvGenre.getText();
        mLanguage=updateTvLanguage.getText();
        mCast=updateTvCast.getText();
        mSynopsis=updateTvSynopsis.getText();
        iframeLink=udateTvIframeLink.getText();
        tvReleaseDate=Integer.valueOf(updateTvReleaseDate.getText());
        mDirectedBy=updateTvShowRunner.getText();
        mRuntime=Integer.valueOf(updateTvRuntime.getText());
        mRating=Double.valueOf(updateTvRating.getText());
        tvSeriesId = Integer.valueOf(updateTvSeriesId.getText());
        noOfSeasons=Integer.valueOf(updateTvNoSeason.getText());
        tvShowRunner=updateTvShowRunner.getText();
        tvSeasonId=Integer.valueOf(updateTvSeasonId.getText());
        tvSeasonName=updateSeasonName.getText();
        tvEpisodeName=updateEpisodeName.getText();
        tvNoOfEpisode=Integer.valueOf(updateTvNoEpisode.getText());
        tvEpisodeId=Integer.valueOf(updateTvEpisodeId.getText());
        //mCover
        //coverFileName
       
        if (mTitle.equals("") || mGenre.equals("") || mLanguage.equals("") || mCast.equals("") ||
                mSynopsis.equals("") || iframeLink.equals("") ||updateTvReleaseDate.getText().equals("") 
                || mDirectedBy.equals("") || updateTvRuntime.getText().equals("") || updateTvRating.getText().equals("")) {
             JOptionPane.showMessageDialog(this, "Please enter data in all the fields");
        }else if(file==null || updateTvCoverImg.getIcon() == null){
        JOptionPane.showMessageDialog(this, "Please Select a cover Image");
        }else{
            
            AdminDatabaseHandler db = new AdminDatabaseHandler();
                    db.connectDatabase();
                    boolean x = db.updateTvSeriesData(mID,mContentType, mTitle, mGenre, mLanguage, mCast, mSynopsis, iframeLink, tvReleaseDate,
                        tvSeriesId, noOfSeasons, tvShowRunner, tvSeasonId, tvSeasonName, tvEpisodeName, tvNoOfEpisode, tvEpisodeId, mRuntime, mRating, coverFileName);
                    if (x) {
                JOptionPane.showMessageDialog(this, "Tv Series Post Updated !!!");
                ViewTvSeriesPost post = new ViewTvSeriesPost();
                post.setVisible(true);
                post.pack();
                post.setLocationRelativeTo(null);
                post.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                this.dispose();
            }else{
                    JOptionPane.showMessageDialog(this, "Tv Series Post Update failed !!!");
                    }
                    updateTvTitle.setText("");
                    updateTvCoverImg.setIcon(null);
                     updateTvId.setText("");
                     updateTvGenre.setText("");
                     updateTvLanguage.setText("");
                     updateTvCast.setText("");
                     updateTvSynopsis.setText("");
                     udateTvIframeLink.setText("");
                     updateTvReleaseDate.setText("");
                     updateTvShowRunner.setText("");
                     updateTvRuntime.setText("");
                     updateTvRating.setText("");
                     updateTvSeriesId.setText("");
                     updateTvNoSeason.setText("");
                     updateTvShowRunner.setText("");
                     updateTvSeasonId.setText("");
                     updateSeasonName.setText("");
                     updateEpisodeName.setText("");
                     updateTvNoEpisode.setText("");
                     updateTvEpisodeId.setText("");
            
        }
        
        
    }//GEN-LAST:event_updateTvSeriesActionPerformed

    public ImageIcon ResizeImage(String ImagePath)
    {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(updateTvCoverImg.getWidth(), updateTvCoverImg.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }
    
    private void updateTvCoverBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTvCoverBrowseActionPerformed
       JFileChooser chooser = new JFileChooser();
       chooser.setCurrentDirectory(new File(System.getProperty("user.home")));
       FileNameExtensionFilter filter = new FileNameExtensionFilter("*.IMAGE", "jpg","gif","png");
       chooser.addChoosableFileFilter(filter);
       int result = chooser.showSaveDialog(null);
        //chooser.showOpenDialog(this);
        if(result == JFileChooser.APPROVE_OPTION){
             file = chooser.getSelectedFile();
             String path = file.getAbsolutePath();
             updateTvCoverImg.setIcon(ResizeImage(path));
             coverFileName = path;
              }
         else if(result == JFileChooser.CANCEL_OPTION){
             System.out.println("No Data");
         }
            
    }//GEN-LAST:event_updateTvCoverBrowseActionPerformed

    private void updateTvRuntimeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_updateTvRuntimeFocusLost
        String runtime=updateTvRuntime.getText();
        if (runtime.length()>3) {
            JOptionPane.showMessageDialog(this,"Invalid length!!! Enter Length between (0-999)");
            updateTvRuntime.setText("");
        }
    }//GEN-LAST:event_updateTvRuntimeFocusLost

    private void updateTvRatingFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_updateTvRatingFocusLost
        
        
        
        
    }//GEN-LAST:event_updateTvRatingFocusLost

    private void updateTvRuntimeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_updateTvRuntimeKeyPressed
        String value = updateTvRuntime.getText();
				int l = value.length();
				if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
					
					
				} else {
					JOptionPane.showMessageDialog(this,"* Enter only numeric digits(0-9)");
			updateTvRuntime.setText("");
				}
    }//GEN-LAST:event_updateTvRuntimeKeyPressed

    private void updateTvRatingKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_updateTvRatingKeyPressed
       String rating = updateTvRating.getText();
        if(rating.length()>3){
        JOptionPane.showMessageDialog(this,"Invalid Rating!!!Insert Like 6.5");
         updateTvRating.setText("");
        }else
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyChar() == '.') {
					
					
				} else {
					JOptionPane.showMessageDialog(this,"* Invalid Rating!!!Insert Like 6.5");
			updateTvRating.setText("");
				}
    }//GEN-LAST:event_updateTvRatingKeyPressed

    private void updateEpisodeNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_updateEpisodeNameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_updateEpisodeNameFocusLost

    private void updateEpisodeNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_updateEpisodeNameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateEpisodeNameKeyPressed

    private void updateTvContentTypeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_updateTvContentTypeFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_updateTvContentTypeFocusLost

    private void updateTvContentTypeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_updateTvContentTypeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateTvContentTypeKeyPressed

    private void updateTvNoEpisodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_updateTvNoEpisodeFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_updateTvNoEpisodeFocusLost

    private void updateTvNoEpisodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_updateTvNoEpisodeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateTvNoEpisodeKeyPressed

    private void updateTvSeasonIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_updateTvSeasonIdFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_updateTvSeasonIdFocusLost

    private void updateTvSeasonIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_updateTvSeasonIdKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateTvSeasonIdKeyPressed

    private void updateTvNoSeasonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_updateTvNoSeasonFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_updateTvNoSeasonFocusLost

    private void updateTvNoSeasonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_updateTvNoSeasonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateTvNoSeasonKeyPressed

    private void updateTvEpisodeIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_updateTvEpisodeIdFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_updateTvEpisodeIdFocusLost

    private void updateTvEpisodeIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_updateTvEpisodeIdKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateTvEpisodeIdKeyPressed

    private void updateSeasonNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_updateSeasonNameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_updateSeasonNameFocusLost

    private void updateSeasonNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_updateSeasonNameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateSeasonNameKeyPressed

    private void updateTvSeriesIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_updateTvSeriesIdFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_updateTvSeriesIdFocusLost

    private void updateTvSeriesIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_updateTvSeriesIdKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateTvSeriesIdKeyPressed

    private void updateTvReleaseDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_updateTvReleaseDateKeyPressed
        String value = updateTvReleaseDate.getText();
				int l = value.length();
				if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
					
					
				} else {
					JOptionPane.showMessageDialog(this,"* Enter only numeric digits(0-9)");
			updateTvReleaseDate.setText("");
				}
    }//GEN-LAST:event_updateTvReleaseDateKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdatetvSeries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdatetvSeries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdatetvSeries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdatetvSeries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdatetvSeries().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminPanelClose;
    private javax.swing.JLabel adminPanelMin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea udateTvIframeLink;
    private javax.swing.JTextField updateEpisodeName;
    private javax.swing.JTextField updateSeasonName;
    private javax.swing.JButton updateTvBack;
    private javax.swing.JTextField updateTvCast;
    private javax.swing.JTextField updateTvContentType;
    private javax.swing.JButton updateTvCoverBrowse;
    private javax.swing.JLabel updateTvCoverImg;
    private javax.swing.JTextField updateTvEpisodeId;
    private javax.swing.JTextField updateTvGenre;
    private javax.swing.JTextField updateTvId;
    private javax.swing.JTextField updateTvLanguage;
    private javax.swing.JTextField updateTvNoEpisode;
    private javax.swing.JTextField updateTvNoSeason;
    private javax.swing.JTextField updateTvRating;
    private javax.swing.JTextField updateTvReleaseDate;
    private javax.swing.JTextField updateTvRuntime;
    private javax.swing.JTextField updateTvSeasonId;
    private javax.swing.JButton updateTvSeries;
    private javax.swing.JTextField updateTvSeriesId;
    private javax.swing.JTextField updateTvShowRunner;
    private javax.swing.JTextArea updateTvSynopsis;
    private javax.swing.JTextField updateTvTitle;
    // End of variables declaration//GEN-END:variables
}
